//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lvh_K22CNT3_Lesson09_Entity_Framework_Database_First.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class lvhMonHoc
    {
        public string LvhMaMH { get; set; }
        public string lvhTenMH { get; set; }
        public Nullable<int> LvhSoTiet { get; set; }
    }
}
