//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lvh_K22CNT3_Lesson09_Entity_Framework_Database_First.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lvhSinhVien
    {
        public string LvhMaSV { get; set; }
        public string LvhHoSV { get; set; }
        public string LvhTenSV { get; set; }
        public Nullable<System.DateTime> LvhNgaySinh { get; set; }
        public Nullable<bool> LvhPhai { get; set; }
        public string LvhNoiSinh { get; set; }
        public string LvhMaKH { get; set; }
        public string LvhHocBong { get; set; }
        public Nullable<decimal> LvhDiemTrungBinh { get; set; }
    
        public virtual lvhKhoa lvhKhoa { get; set; }
    }
}
